# LinkedIn Knowledge Management System - Google App Engine Configuration

runtime: python311
service: default
instance_class: F2  # Can be upgraded to F4 or higher

# Scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Environment variables
env_variables:
  ENVIRONMENT: production
  SERVER_HOST: 0.0.0.0
  SERVER_PORT: 8080
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  
  # Storage paths (using Cloud Storage)
  KNOWLEDGE_REPO_PATH: /tmp/knowledge_repository
  CACHE_DB_PATH: /tmp/cache/knowledge_cache.db
  LOG_FILE_PATH: /tmp/logs/linkedin_kms.log
  
  # Logging
  ENABLE_FILE_LOGGING: "false"  # Use Cloud Logging instead
  LOG_LEVEL: INFO
  
  # Security
  ENABLE_PII_DETECTION: "true"
  SANITIZE_CONTENT: "true"
  
  # CORS (update with your domain)
  CORS_ALLOW_ORIGINS: https://your-project.appspot.com
  
  # Rate limiting
  API_RATE_LIMIT_REQUESTS_PER_MINUTE: "100"
  GEMINI_RATE_LIMIT_RPM: "15"
  
  # Cloud services
  GOOGLE_CLOUD_PROJECT: your-project-id
  USE_CLOUD_STORAGE: "true"
  USE_CLOUD_SQL: "false"  # Set to true if using Cloud SQL
  USE_CLOUD_LOGGING: "true"

# Health check
readiness_check:
  path: /api/v1/health
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: /api/v1/health
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Resource limits
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# Network settings
network:
  forwarded_ports:
    - 8080

# Handlers for static files
handlers:
  # Static files
  - url: /static
    static_dir: linkedin_scraper/api/static
    secure: always
    
  # API routes
  - url: /api/.*
    script: auto
    secure: always
    
  # Main application
  - url: /.*
    script: auto
    secure: always

# Skip files during deployment
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?tests/.*$
  - ^(.*/)?test_.*\.py$
  - ^(.*/)?.*_test\.py$
  - ^(.*/)?venv/.*$
  - ^(.*/)?\.venv/.*$
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?\.git/.*$
  - ^(.*/)?\.github/.*$
  - ^(.*/)?docker.*$
  - ^(.*/)?Dockerfile.*$
  - ^(.*/)?\.dockerignore$
  - ^(.*/)?README\.md$
  - ^(.*/)?\.env.*$